application: pushcontacts
version: 1
runtime: python
api_version: 1

handlers:
    
- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/images
  static_dir: static/images
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /test.*
  login: admin
  script: gaeunit.py
    
- url: .*
  script: main.py
  
inbound_services:
- xmpp_message
  

